### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by ldittmar81** [sebilm/ioBroker.nibeuplink#1]
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

**Comment by sebilm** [comment]
Changed to current template - so compact mode is now supported in version 0.2.0.

**Comment by sebilm** [comment]
The compact mode was disabled then, but in version 0.4.0 it works now.
