### ISSUE TITLE
Fan Speed wird nicht mehr updated seit 20.1.2022

### ISSUE THREAD

**Issue by tops4u** [sebilm/ioBroker.nibeuplink#100]
**Describe the bug**  
UNIT_1.CPR_INFO_EP14.FAN_SPEED_EB101 wird seit dem 20.1. nicht mehr updated. Leider ist das im NibeUplink Portal nicht sichtbar. Daher weiss ich nicht, ob es ein Problem bei NibeUplink oder dem Adapter ist. Ich habe 2 Instanzen und beide haben Punkt 20.1. 16:09 den letzten Update geliefert.  Ebenfalls betroffen ist UNIT_1.CPR_INFO_EP14.INJECTION_EB101_EP14_BT81

Es handelt sich dabei einmal um eine F2120-12 und eine F2120-16. Die -12 hat noch alte SW die -16 neue. Ich habe an der -12 ebenfalls einen MQTT Raspi dran, dort kommen die Daten (über ModBus) 

**Screenshots & Logfiles**  
<img width="266" alt="image" src="https://user-images.githubusercontent.com/6877067/154355726-d99e63f8-6e8e-48f6-99cd-a017d295a315.png">

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 5.1.25
 - Node version: 12.21.0
 - Operating system: linux (arm)

**Comment by sebilm** [comment]
FAN_SPEED_EB101 müsste Parameter 41002 sein, INJECTION_EB101_EP14_BT81 müsste 41164 sein. Du kannst bei der Instanze im ioBroker das Loglevel auf "Alles" stellen. Dabei sollte der Adapter auch neu gestartet werden. Wenn nicht, dann den Adapter neu starten. Dann auf Protokolle wechseln und dort das Loglevel auf "silly" stellen. Da gibts dann einen "silly"-Eintrag vom NibeUplink-Adapter, der ziemlich groß ist und alles enthält, was Nibe gesendet hat. Wenn dort die beiden Bezeichner oder die beiden ParameterIds nicht vor kommen, dann sendet die Nibe nicht mehr mit. Wenn sie dort vor kommen, könnte ich den Logeintrag brauchen. Außerdem wäre interessant, ob der NibeUplink-Adapter sonst noch was auffälliges loggt - also Warning oder Error. Generell landet halt nur das in dem Objekt-Baum, was Nibe sendet.
Falls Nibe es nicht mehr mit sendet, kannst du es über die neue Option Manage/Verwalten explizit holen lassen. Dann dort die UnitId 1 und die beiden ParameterIds eintragen. Oben den Haken zum Aktivieren nicht vergessen.

**Comment by sebilm** [comment]
@tops4u Hast du das Problem weiter untersucht?

**Comment by tops4u** [comment]
@sebilm scheinbar wird der Wert tatsächlich nicht mehr übertragen. Das ist etwas Schade. In der NIBE App selbst sieht man den Wert, scheinbar wurde er im API jedoch entfernt.

**Comment by sebilm** [comment]
Danke für die Rückmeldung. Du kannst ja mal bei Nibe anfragen.
