### ISSUE TITLE
Missing values for systemunits

### ISSUE THREAD

**Issue by steffenkuss** [sebilm/ioBroker.nibeuplink#11]
Hello,
in my setup (Nibe F2120 with SMO40) there are two sections on the nibeuplink service info page. See screenshot

![image](https://user-images.githubusercontent.com/16925390/96853612-da7a6a80-145a-11eb-8244-519584efe428.png)

All information of the "slave" section are missing. On the "slave" section there are important information like compressor starts, and operation time.

Best regards

**Comment by Huseriato** [comment]
Hey, I don't have a solution, but want to push this. The Slave 1 information is also missing in my objects. Are there any chances to add them?

**Comment by sebilm** [comment]
I will see. Ich hope I have time to do it in december.

**Comment by steffenkuss** [comment]
can you give any information about how to inplement this feature? maybe i can help a little bit or test it local.

**Comment by Huseriato** [comment]
I did not manage to find out, how to install or run this adapter locally to test this in an development environment (I've never created an adapter for iobroker). But it seems so, that there is no call to the /units API-call in any file of this adapter. 

I thing SMO 40 and Slave 1 are different units. You can use the documentation here to play with the api: https://api.nibeuplink.com/docs/v1/Functions - Authentication is done via your nibe uplink account. I think it would help to find the correct api call to get information about Slave 1 (or maybe Slave 2, 3, n in other scenarios).

**Comment by Huseriato** [comment]
Hey, can I do anything to help you out? I'm really missing those values and want to log them. :)

**Comment by sebilm** [comment]
Time, I need time. But I had to work 2 days. I think I have time then.

**Comment by sebilm** [comment]
I am not sure, what "SMO 40" and "Slave 1" are. Can you show me a screenshot with more information arround?

The adapter gets the categories via https://api.nibeuplink.com/docs/v1/Api/GET-api-v1-systems-systemId-serviceinfo-categories_systemUnitId_parameters and then get all data from every category.

But I'm not sure if SMO 40 and Slave 1 are categories.

My Nibe F1245-6 has categories like ADDITION, AUX_IN_OUT, STATUS, ... - these categories you can see in iobroker as the first level under "nibeuplink.0" in the objects.

**Comment by steffenkuss** [comment]
I think "SMO40" and "Slave 1" are systemunits and you can get all systemunits with this endpoint: api/v1/systems/{systemId}/units
In your call to get categories you use systemunit 0 (default)?

**Comment by sebilm** [comment]
Ah, I see. Thank you. Thats a bigger change. This may take a few days. I need to fix a few bugs first.

**Comment by sebilm** [comment]
So this feature is now in the master branch. Can you please install the adapter directly from GitHub to test it?
But read the change log first:
https://github.com/sebilm/ioBroker.nibeuplink/blob/master/README.md#changelog

And tell me if it is working.

**Comment by steffenkuss** [comment]
Looks great:

![image](https://user-images.githubusercontent.com/16925390/102893971-af17fa00-4462-11eb-99fa-bce656b01913.png)

Some values are not correct (need division by 10) but there is already another issue related to that topic.
Thanks a lot!

**Comment by Huseriato** [comment]
Yes, works here, too. Great job. Thank you.

**Comment by Huseriato** [comment]
@steffenkuss I think you have to take a look, if your values that need a division by 10 are the same as mine. We have different external units. So there might be other objects.
