### ISSUE TITLE
Bekomme dauerhaft 400 error

### ISSUE THREAD

**Issue by StephiCGN** [sebilm/ioBroker.nibeuplink#15]
Hallo Seb

erstmal danke für deinen Adapter, habe deine gut geschriebene Anleitung befolgt und auch das mit dem AuthCode hat alles einwandfrei funktioniert.
Leider bleibt der State im IOBroker auf gelb mit der Fehlermeldung "Verbunden mit NibeUplink" Falsch
Im Log bekomme ich: 

nibeuplink.0 | 2021-04-04 00:22:48.151 | error | (xxx) Error: Response Error: 400 Bad Request
-- | -- | -- | --
nibeuplink.0 | 2021-04-04 00:22:47.988 | info | (xxx) Adapter started.
nibeuplink.0 | 2021-04-04 00:22:47.854 | info | (xxx) Starting adapter.
nibeuplink.0 | 2021-04-04 00:22:47.821 | info | (xxx) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.nibeuplink, node: v12.21.0, js-controller: 3.1.6

Ist kein Leerzeichen angehangen, die Werte sollten stimmen.

Danke und beste Grüße

**Comment by sebilm** [comment]
Also ich kenne die 400 mit dem Bad Request bisher nur, wenn der Auth Code nicht richtig eingetragen wurde. Bitte nochmal alles der Reihe nach durchgehen und schauen, dass alles richtig eingetragen ist und einen neuen AuthCode holen und eintragen. Mehr kann ich da ohne genauere Infos nicht dazu sagen.
Wenn das nicht hilft, könnte ich höchstens noch eine TeamViewer-Session anbieten.

**Comment by StephiCGN** [comment]
Moin

 

Vielen Dank für deine Rückmeldung und danke für das Angebot mit TV

Habe ich bereits mehrfach probiert auch unter Nibe eine weitere Applikation eingegeben.

Finde den Fehler leider nicht.

Wann könnte es dir passen? Irgendwann abends mal möglich?

Beste Grüße

Stephan

 

Von: sebilm ***@***.***> 
Gesendet: Dienstag, 6. April 2021 19:21
An: sebilm/ioBroker.nibeuplink ***@***.***>
Cc: StephiCGN ***@***.***>; Author ***@***.***>
Betreff: Re: [sebilm/ioBroker.nibeuplink] Bekomme dauerhaft 400 error (#15)

 

Also ich kenne die 400 mit dem Bad Request bisher nur, wenn der Auth Code nicht richtig eingetragen wurde. Bitte nochmal alles der Reihe nach durchgehen und schauen, dass alles richtig eingetragen ist und einen neuen AuthCode holen und eintragen. Mehr kann ich da ohne genauere Infos nicht dazu sagen.
Wenn das nicht hilft, könnte ich höchstens noch eine TeamViewer-Session anbieten.

**Comment by sebilm** [comment]
In der README.md steht meine E-Mail-Adresse. Bitte schreibe mir direkt an diese Adresse, dann können wir das privat ausmachen.
