### ISSUE TITLE
Daily error msg

### ISSUE THREAD

**Issue by soulfire89** [sebilm/ioBroker.nibeuplink#215]
**Describe the bug**  
nibeuplink.0 | 2023-03-18 06:48:36.175 | error | AxiosError: timeout of 45000ms exceeded
nibeuplink.0 | 2023-03-18 06:48:36.169 | error | error from serviceinfo/categories?parameters=true&systemUnitId=0

**To Reproduce**  
Restart adapter, error appears once a day

**Versions:**  
 - Adapter version: <v1.2.1>
 - JS-Controller version: <v16.19.1> <!-
 - NPM: 8.19.3
 - Operating system: <docker>

**Additional context**  
No Nibe premium connectivity, just read and connect

**Comment by sebilm** [comment]
I also have the error. I have created a new version of the adapter with all dependencies updated (also Axios) - the error still occurs. I think the error is at Nibe, because it occurred without changing the adapter and because it is a typical timeout.
