### ISSUE TITLE
Change Nibe Settings with NibeUplinkPremium possible?

### ISSUE THREAD

**Issue by dagoellner** [sebilm/ioBroker.nibeuplink#219]
Hello thanks for the Great Adapter. I would love to change the settings of my Nibe using IOBROKER. Would it be possible to use this Adapter to change settings together with NibeUplinkPremium ?

**Comment by sebilm** [comment]
Hello,

you can change settings via Manage/Write-Support. See: https://github.com/sebilm/ioBroker.nibeuplink/blob/master/README.md#managewrite-support
Because of limitations of nibeuplink you can only change a few settings.
