### ISSUE TITLE
Add Parameter only Integer allowed

### ISSUE THREAD

**Issue by joisphe** [sebilm/ioBroker.nibeuplink#241]
![image](https://github.com/sebilm/ioBroker.nibeuplink/assets/55396289/5aab8a77-3d92-4120-8fee-8dc52513b892)

Parameter doesn't have only ID Numbers, is it possible to extend this field and the code to allow a string?

![image](https://github.com/sebilm/ioBroker.nibeuplink/assets/55396289/b729dcf1-d634-491a-8dab-696a3adf0c23)

Thank you

**Comment by sebilm** [comment]
These IDs have also numbers:

hot_water_boost -> 48132
ventilation_boost -> 47260

seb

**Comment by joisphe** [comment]
Great man!! Thank you very much!
