### ISSUE TITLE
myuplink.com Support

### ISSUE THREAD

**Issue by mhuber77** [sebilm/ioBroker.nibeuplink#266]
Hi, 

today i received an email from nibe. I can swap to their new portal [https://myuplink.com]. Do you support this portal too or is it planed to upgrade the adapter!?
thanks and best regards
markus

**Comment by mhuber77** [comment]
I know in this adapter myuplink isn't supported, but nibe will discontinue nibeuplink for all their pumps....

**Comment by sebilm** [comment]
I did not get such a mail from nibe but if my F1245 will work with myuplink, I will support it.

**Comment by m-s-b** [comment]
Sounds good ;-) F1245 is supported. I also didn't receive any information, but you can Log in withe the Same credentials and nibe will convert IT.

**Comment by sebilm** [comment]
Do you know if you can operate myUplink and Nibe Uplink with one heat pump at the same time? Will Nibe Uplink continue to work with my heat pump if I register it with myUplink?

**Comment by m-s-b** [comment]
@sebilm 
Nope, weiß ich nicht, hab mich nicht getraut meinen Nibeuplink-Account zu riskieren. 
Evtl. hat @mhuber77 ja mehr Infos dazu. Im Zweifel teste ich nächste Woche mal was passiert wenn ich einen MyUplink-Zugang anlege.

**Comment by mhuber77** [comment]
> @m-s-b Do you know if you can operate myUplink and Nibe Uplink with one heat pump at the same time? Will Nibe Uplink continue to work with my heat pump if I register it with myUplink?

As I know you can only use nibeuplink or myuplink with one pump. I think you need to rewrite the adapter to support both APIs, there also an API for myuplink available, see https://dev.myuplink.com/login

**Comment by sebilm** [comment]
I couldn't add my heat pump to myuplink, but I found a way to read out the demo system. I think I will write a new adapter for myuplink. I will then link it here.

**Comment by mhuber77** [comment]
befor you  can add your pump, you need to update your pump/system, in my case i found the update here -> [https://www.nibe.eu/de-de/nibe-uplink-to-myuplink?HPModel=nibe-e8]

**Comment by FlorianSchulze** [comment]
> I couldn't add my heat pump to myuplink, but I found a way to read out the demo system. I think I will write a new adapter for myuplink. I will then link it here.

Sebilm, i just started a new fresh installation with a NIBE S1255 on myuplink.com - no longer compatible with older versions. maybe I can provide you access to this system as a small support to your work? we do not urgently need a solution, just started the setup and integration in iobroker is planned for in advance - so just if that would help, let me know,
cheers,
florian

**Comment by sebilm** [comment]
If anyone wants to test it, the adapter is available via GitHub: https://github.com/sebilm/ioBroker.myuplink.git

Unfortunately, myUplink does not send back a refresh token, so the adapter currently only runs for one hour and then you have to get a new AuthCode.

**Comment by FlorianSchulze** [comment]
> If anyone wants to test it, the adapter is available via GitHub: https://github.com/sebilm/ioBroker.myuplink.git
> 
> Unfortunately, myUplink does not send back a refresh token, so the adapter currently only runs for one hour and then you have to get a new AuthCode.

will do and start it tonight. any debug-log you want or just "sniff" if it works basically?

**Comment by FlorianSchulze** [comment]
<img width="1364" alt="Screenshot 2023-12-20 at 22 39 12" src="https://github.com/sebilm/ioBroker.nibeuplink/assets/40965321/0b9c0277-bdd7-4445-a682-54c50f436091">

**Comment by FlorianSchulze** [comment]
First view, works as expected. The naming of the parameters seems to be missing, but is understandable. Heating system is detected automatically and without any issues from the first view.

**Comment by mhuber77** [comment]
sorry I can't test with my pump, I've troubles to upgrade my pump to support myuplink, nibe support case is open...I'm not sure if they fix the problems during the holidays

**Comment by sebilm** [comment]
@FlorianSchulze Does it work longer than one hour without relogin?
I think the naming is correct, but your object tree does not show the whole name but only the first letter. I choose the IDs of the system, the device and the data points as IDs for the objects in the objects tree because these are the only unique IDs.

**Comment by FlorianSchulze** [comment]
@sebilm no - as you mentioned it raises errors after one hour. One detail, the status "connected" stays "true", so from data perspective you dont see the system is detached. But you see it in the logs and the adapter status. So, briliant work for the first approach! Guess, Prio is token now, cant believe there is no solution from nibe to manage TTL from the token by getting a new one?

**Comment by sebilm** [comment]
I am waiting for an answer from myuplink support.

**Comment by sebilm** [comment]
I have opened an issue directly at the new adapter for further discussions - please continue to discuss there:

https://github.com/sebilm/ioBroker.myuplink/issues/1
