### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by teuti** [sebilm/ioBroker.nibeuplink#290]
Moin,

ich habe seit ein paar Tagen das Problem, dass ich keine Werte mehr erhalten. Im Log nachgeschaut konnte ich sehen, dass es Probleme mit mit oauth gab ("error from /oauth/token").

Daraufhin habe ich in den Einstellungen der NibeUpLInk-Instanz auf de Link geklickt, um den OAuth-Code zu generieren. Als Fehlermeldung erhielt ich "something went wrong". Weitere Informationen werden leider nicht geliefert. Auch das Erstellen einer neuen Anwendung bei api.nibeuplink.com hat nicht geholfen.

Ist das Problem bekannt? 

gruß,
teuti

**Comment by sebilm** [comment]
Also bei mir läuft alles wie bisher. Es lief einfach nicht, ohne dass du was geändert hast? Also auch ohne dass du einen neuen AuthCode geholt hast? Ich denke, dann liegt der Fehler eher bei Nibeuplink. Hast du eventuell eine E-Mail bekommen, dass du auf myUplink umstellen sollst? Nibe stellt scheinbar grad alle Wärepumpen auf myUplink um. Du könntest noch testen, ob die Nibeuplink-App auf dem Handy bei dir funktioniert.

**Comment by teuti** [comment]
Ja, das übliche. Von heute auf morgen hat es nicht mehr funktioniert, ohne dass der Benutzter etwas getan hat. ;)

AuthCode und so alles das gleiche geblieben. Ich habe ne F1255, die mit der aktuellsten Firmware noch nicht auf myUplink umgestellt werden kann. Nibeuplink funktioniert auch weiterhin.

Im Log von ioBroker steht

Error: Bad Request: { "error": "invalid_request" }
| error | error from /oauth/token

Spontan noch eine Idee? Sonst schaue ich mal, wie ich das hier debuggen kann bzw. ich baue mir selber mal einen Requst auf und schaue.

**Comment by sebilm** [comment]
Es gab mal Leute, die hatten Probleme, weil beim Copy & Paste von Identifyer, Secret oder AuthCode am Ende ein Leerzeichen mit kopiert wurde. Das gab's ähnliche Effekte. Deshalb hab ich gefragt, ob du was geändert hast. Du könntest nochmal schauen, dass keine Leerzeichen zu viel sind.

**Comment by teuti** [comment]
Wunderwerk Technik. Es läuft jetzt.. Geändert habe ich aber nichts, nur noch mal den Link angeklickt, um den Auth-Code zu generieren.

Leerzeichen am Ende von Identifier, Secret und Callback-URL lag es nicht. Wenn ich jetzt dort ein Leerzeichen einfüge, wird der AuthCode generiert. Das gleich auch mit einem Leerzeichen am Anfang vom Secret. Lediglich ein Leerzeichen am Anfang vom Identifier meldet den Fehler "Failure looking up secret for client or token."

Die Fehlermeldung "something went wrong" kann ich nicht mehr reproduzieren.
