### ISSUE TITLE
Anbindung Nibe S1255

### ISSUE THREAD

**Issue by MaAr389** [sebilm/ioBroker.nibeuplink#308]
Hallo,

ist es korrekt, dass die Anbindung einer S-Serie (Nibe S1255) derzeit nicht möglich ist? 
Ich bin bereits seit Beginn bei "myuplink" und habe heute den Adapter im ioBroker ausgetestet, leider ohne Erfolg. 

nibeuplink.0 | 2024-07-17 07:42:40.791 | error | Error: Bad Request: { "error": "invalid_request" }
nibeuplink.0 | 2024-07-17 07:42:40.791 | error | error from /oauth/token

Entweder ist mir ein Fehler unterlaufen, oder es funktioniert wirklich nicht. 

Viele Grüße
Martin

**Comment by sebilm** [comment]
Die S-Serie funktioniert in der Tat nicht mit Nibeuplink, sondern nur mit myuplink. Auch die F-Serie wird auf myuplink umgestellt. Deshalb existiert sei etwa Anfang des Jahres der myuplink-Adapter: https://github.com/sebilm/ioBroker.myuplink
