### ISSUE TITLE
Value for avg. outdoor temp (BT1) wrong

### ISSUE THREAD

**Issue by FlorianSchulze** [sebilm/ioBroker.nibeuplink#312]
Hi Seb,

having a 95 degree outside air temperature (correct value!), correctly displayed in MyUplink, the Adapter tells 9.9 degrees. This temp value is used in some HPs if cooling is active to avoid compressor starts. Is this an overflow of a value? Any debug information I can provide?

{
  "type": "state",
  "common": {
    "name": "avg. outdoor temp (BT1)",
    "type": "number",
    "role": "value",
    "unit": "°C",
    "read": true,
    "write": false
  },
  "native": {},
  "from": "system.adapter.nibeuplink.0",
  "user": "system.user.admin",
  "ts": 1722437503662,
  "_id": "nibeuplink.0.UNIT_0.STATUS.AVG_OUTDOOR_TEMP_BT1",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Cheers,
Florian

**Comment by sebilm** [comment]
Do you use myuplink or nibeuplink? You can't use both. And I don't change anything at the nibeuplink adapter because nibe will shut down nibeuplink in 2 weeks.
