### ISSUE TITLE
Please check ioBroker.nibeuplink with js-controller 2.0

### ISSUE THREAD

**Issue by ioBrokerChecker** [sebilm/ioBroker.nibeuplink#7]
Hi,

the new js-controller 2.0 will come into latest repository in the next days and we want to make sure that all adapters are working well. We already did a 2 weeks Beta test and so some adapter were aleady checked and some needed slight adjustments.

You can find more information in https://github.com/ioBroker/ioBroker.js-controller/issues/482 and in the ioBroker Forum. If you have more technical questions please write in the referenced issue or in the Developer thread please. General questions are best in the genral thread.

Please update your systems to js-controller 2.0 and check your adapter.

Please close this issue once you have checked your adapter or received successfull reports from users.

Thank you very much for your support. Please contact us in the other Threads or Forum on any question.

**Comment by sebilm** [comment]
I took the current template for version 0.2.0 on 2019-03-16 which was already compatible to js-controller 2.0. Today I installed the js-controller 2.0 on a test system and also my adapter. It works. I close the ticket.
