### ISSUE TITLE
Nibe myuplink

### ISSUE THREAD

**Issue by andremueller83** [sebilm/ioBroker.nibeuplink#73]
Hallo lieber Entwickler,
gibt es Pläne einen Adapter für "myuplink" von NIBE zu entwickeln?
Ich habe seit 2020 eine VVM S320 Innenheit welche über "myuplink" steuerbar ist.
Wenn nein, gibt es Möglichkeiten das Vorgängertool Nibe Uplink dafür zu verwenden?

**Comment by sebilm** [comment]
Hallo,

ich mache dir da wenig Hoffnung, da mir momentan nicht nur die Zeit dafür fehlt, sondern auch eine passende Heizung.

Du kannst aber eine Adapter-Anfrage machen - vielleicht findet sich ja jemand, der einen entsprechenden Adapter programmiert. Da kann man vielleicht diesen Adapter hier als Vorlage nehmen. Die Anfrage kannst du hier stellen:
https://github.com/ioBroker/AdapterRequests
Dort die Anleitung lesen und dann unter Issues einen neuen Issue eintragen.

Weiterhin scheint es so zu sein, dass die neuere Nibe-Geräte Modbus-TCP können. Diese könntest du dann über den Modbus-TCP-Adapter ansprechen. Das ist dann aber nicht so kompfortabel und man muss wissen, was welches Modbus-Register tut. Vielleicht findet sich dazu ja was im Internet.

seb
